config/routes.rb
Talks::Application.routes.draw do
  resources :users, :only => [:create, :show]
  resources :talks, :only => [:index, :create, :show]
  
  resources :session, :only => [:create, :destroy]

  root :to => 'homepage#show'
end

app/models/talk.rb
class Talk < ActiveRecord::Base

  validates :title, presence: true

  belongs_to :user

  before_save :uri?

  def uri?
    uri = URI.parse(self.youtube_url)
    uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :talks

  def to_param
    self.username
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include AuthenticationConcern

  before_action :ensured_logged_in

  def ensured_logged_in
    redirect_to root_path unless logged_in?
  end
end

app/controllers/concerns/authentication_concern.rb
module AuthenticationConcern
  extend ActiveSupport::Concern
  
  def logged_in?
    current_user.present?
  end

  def current_user
    if session[:user_id]
      return @current_user ||= User.find(session[:user_id])
    end
    false
  end

  def teacher
    current_user.teacher == true
  end

  module ClassMethods
  end

  module InstanceMethods
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  skip_before_action :ensured_logged_in  
  
  def show
    @user = User.new
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  skip_before_action :ensured_logged_in

  def create
    session.clear
    @user  = User.find_by_username(params[:username])
    
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), :notice => "You've successfully logged in"
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  include AuthenticationConcern
  
  def show
    @talk = Talk.find(params[:id])
    @user  = current_user
  end

  def index
    @talks = Talk.all
    @user  = current_user
  end

  def create
    if teacher 
      @talk = Talk.new(talk_parameters)
      if @talk.save
        redirect_to talk_path(@talk)
      else
        redirect_to user_path(current_user)
      end
    else
      redirect_to root_path
    end
  end


  private
  def talk_parameters
    params.require(:talk).permit(:title, :content, :youtube_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def create
    session.clear
    @user = User.new(user_profile_parameters)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @user.errors.delete(:password_digest)
      flash[:error] = @user.errors.full_messages
      redirect_to root_path
    end
  end

  def show
    @user = current_user
    @talk = Talk.new
  end

  private 
  def user_profile_parameters
    params.require(:user).permit(:username, :password, :password_confirmation, :teacher)
  end

  def talk_parameters
    params.require(:talk).permit(:title, :content, :youtube_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper 
  def current_user
    if session[:user_id]
      return @current_user ||= User.find(session[:user_id])
    end
    false
  end

  def teacher
    if session[:user_id]
      @current_user = User.find(session[:user_id])
      if @current_user.teacher == true
        @current_user
      else
        false
      end
    else
      false
    end
  end
end

app/views/homepage/show.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :username, :placeholder => "Username" %>
  <%= f.password_field :password, :placeholder => "Password" %>
  <%= f.password_field :password_confirmation, :placeholder => 'Password Confirmation' %>
  <%= f.label :teacher %>
  <%= f.check_box :teacher %>
  <%= f.submit 'Signup' %>
<% end %>

<%= form_tag session_index_path do %>
  <%= text_field_tag :username, nil, :placeholder => "Username"  %>
  <%= password_field_tag :password, nil, :placeholder => "Password"  %>
  <%= submit_tag 'Login' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Talks</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/main.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :username, :placeholder => "Username" %>
  <%= f.text_field :password, :placeholder => "Password" %>
  <%= f.text_field :password_confirmation, :placeholder => 'Password Confirmation' %>
  <%= f.label :teacher %>
  <%= f.check_box :teacher %>
  <%= f.submit 'Signup' %>
<% end %>

<%= form_tag session_login_path %>
  <%= text_field_tag :username, nil, :placeholder => "Username"  %>
  <%= text_field_tag :password, nil, :placeholder => "Password"  %>
  <%= submit_tag 'Login' %>

app/views/talks/index.html.erb
<% if @talks %>
  <ul>
    <% @talks.each do |talk| %>
      <li><%= link_to talk.title, talk_path(talk) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to "Profile ", user_path(@user) %>

app/views/talks/show.html.erb
<h1><%= @talk.title %></h1>

<iframe width="853px" height="480px" src="<%= @talk.youtube_url %>" frameborder="0" allowfullscreen></iframe>

<p><%= @talk.content %></p>

<%= link_to "View Talks", talks_path %>
<%= link_to "Profile ", user_path(@user) %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>
<h2>You're in!</h2>
<% if @user.teacher %>
	<h3>Teacher</h3>
  <%= form_for @talk do |f| %>
    <%= f.text_field :title, :placeholder => "Title" %>
    <%= f.text_field :content, :placeholder => "Content" %>
    <%= f.text_field :youtube_url, :placeholder => 'Youtube URL' %>
    <%= f.submit 'Create talk' %>
  <% end %>
<% else %>
  <h3>Boot</h3>
<% end %>
<%= link_to "View Talks", talks_path %>
<%= link_to "Logout", session_path, :method => 'delete' %>